{{- if .Values.clickhouse.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-clickhouse-credentials
  labels:
    {{- include "rybbit.labels" . | nindent 4 }}
type: Opaque
stringData:
  user: {{ .Values.clickhouse.auth.username | default "default" | quote }}
  password: {{ .Values.clickhouse.clickhouse.defaultUser.password | default "changeme" | quote }}
{{- end }}
