apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-client
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rybbit.labels" $ | nindent 4 }}
    app.kubernetes.io/component: client
spec:
  type: {{ .Values.client.service.type }}
  ports:
    - port: {{ .Values.client.service.port }}
      targetPort: {{ .Values.client.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "rybbit.selectorLabels" $ | nindent 4 }}
    app.kubernetes.io/component: client