{{- /*
  Generate secrets for components that need passwords.
  Only created if no existing secret is provided.
*/ -}}

{{- /* Better Auth secret */ -}}
{{- if and .Values.backend.enabled (not .Values.backend.betterSecret.secretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-better-auth
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rybbit.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  {{ .Values.backend.betterSecret.authKey | default "better-auth-secret" }}: {{ randAlphaNum 32 | b64enc | quote }}
{{- end }}
