{{- if .Values.valkey.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-valkey
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rybbit.labels" . | nindent 4 }}
    app.kubernetes.io/component: valkey
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 6379
      targetPort: valkey
      protocol: TCP
      name: valkey
  selector:
    {{- include "rybbit.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: valkey
{{- end }}
