name: Helm Chart CI/CD

on:
  push:
    tags:
    - 'v*-rc'
    # paths:
    # - '**/*.yaml'
    # - 'templates/**'
    # - 'Chart.yaml'
    # - 'values.yaml'
    # - 'test/**'
  workflow_dispatch:


env:
  REGISTRY: harbor.lag0.com.br
  CHART_NAME: rybbit

jobs:
  publish:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: set version
      run: |
        ref=${GITHUB_REF##*/}
        echo "VERSION=${ref#v}" >> $GITHUB_ENV
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.12.3

    - name: Login to OCI Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - name: Print env.VERSION
      run: |
        echo "env.VERSION: ${{ env.VERSION }}"
    - name: Package and Push Helm Chart
      run: |
        echo "=== Updating dependencies ==="
        helm dependency update .
        echo "✓ Dependencies updated successfully"

        echo "=== Packaging chart ==="
        helm package --version ${{ env.VERSION }} .
        echo "✓ Chart packaged successfully"

        echo "=== Pushing to OCI registry ===" 
        helm push rybbit-*.tgz oci://${{ env.REGISTRY }}/library
