name: Helm Chart CI/CD

on:
  push:
    branches:
    - main
    tags:
    - 'v*'
    # paths:
    # - '**/*.yaml'
    # - 'templates/**'
    # - 'Chart.yaml'
    # - 'values.yaml'
    # - 'test/**'
  workflow_dispatch:


env:
  REGISTRY: harbor.lag0.com.br # Change this to your OCI registry
  CHART_NAME: rybbit

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.12.3

    - name: Install yq
      run: |
        echo "=== Installing yq ==="
        wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
        chmod +x /usr/local/bin/yq
        echo "✓ yq installed successfully"

    - name: Install k3s
      run: |
        echo "=== Installing k3s ==="
        curl -sfL https://get.k3s.io | sh -
        sudo chmod 644 /etc/rancher/k3s/k3s.yaml
        mkdir -p ~/.kube
        sudo cp /etc/rancher/k3s/k3s.yaml ~/.kube/config
        sudo chown $USER:$USER ~/.kube/config
        export KUBECONFIG=~/.kube/config
        echo "✓ k3s installed successfully"

    - name: Wait for k3s to be ready
      run: |
        echo "=== Waiting for k3s to be ready ==="
        timeout 60s bash -c 'until kubectl get nodes; do sleep 2; done'
        echo "✓ k3s is ready"

    # - name: Install Prometheus Operator CRDs
    #   run: |
    #     echo "=== Installing Prometheus Operator CRDs ==="
    #     # Install ServiceMonitor CRD
    #     kubectl apply -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/main/example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
    #     # Install Prometheus CRD
    #     kubectl apply -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/main/example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
    #     # Install PrometheusRule CRD
    #     kubectl apply -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/main/example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml
    #     # Install Alertmanager CRD
    #     kubectl apply -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/main/example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
    #     # Install PodMonitor CRD
    #     kubectl apply -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/main/example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
    #     # Install Probe CRD
    #     kubectl apply -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/main/example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml
    #     # Install ThanosRuler CRD
    #     kubectl apply -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/main/example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml

    #     echo "=== Waiting for CRDs to be ready ==="
    #     kubectl wait --for=condition=established --timeout=60s crd/servicemonitors.monitoring.coreos.com
    #     kubectl wait --for=condition=established --timeout=60s crd/prometheuses.monitoring.coreos.com
    #     kubectl wait --for=condition=established --timeout=60s crd/prometheusrules.monitoring.coreos.com
    #     kubectl wait --for=condition=established --timeout=60s crd/alertmanagers.monitoring.coreos.com
    #     kubectl wait --for=condition=established --timeout=60s crd/podmonitors.monitoring.coreos.com
    #     kubectl wait --for=condition=established --timeout=60s crd/probes.monitoring.coreos.com
    #     kubectl wait --for=condition=established --timeout=60s crd/thanosrulers.monitoring.coreos.com
    #     echo "✓ Prometheus Operator CRDs installed and ready"

    - name: Create test directories
      run: |
        echo "=== Creating test directories ==="
        mkdir -p test/output test/logs
        echo "✓ Test directories created successfully"

    - name: Update Helm dependencies
      run: |
        if [ ! "$(ls -A charts)" ]; then
          echo "=== Updating Helm dependencies ==="
          helm dependency update .
          echo "✓ Helm dependencies updated successfully"
        else
          echo "=== Using existing dependencies ==="
          echo "✓ Using existing dependencies"
        fi

    - name: Generate templates
      id: generate
      run: |
        for test_file in test/test-cases/*.yaml; do
          test_name=$(basename "$test_file" .yaml)
          echo "=== Generating template for: $test_name ==="
          helm template rybbit . -f "$test_file" > "test/output/${test_name}-output.yaml"
          echo "✓ Template generated successfully for $test_name"
        done

    - name: Validate YAML syntax
      run: |
        for test_file in test/test-cases/*.yaml; do
          test_name=$(basename "$test_file" .yaml)
          echo "=== Validating YAML for: $test_name ==="
          if ! yq eval '.' "test/output/${test_name}-output.yaml" > /dev/null 2>&1; then
            echo "Invalid YAML syntax in ${test_name}-output.yaml"
            yq eval '.' "test/output/${test_name}-output.yaml"
            exit 1
          fi
          echo "✓ YAML syntax validated successfully for $test_name"
        done

    - name: Check for unrendered templates
      run: |
        for test_file in test/test-cases/*.yaml; do
          test_name=$(basename "$test_file" .yaml)
          echo "=== Checking for unrendered templates in: $test_name ==="
          if grep -q "{{.*}}" "test/output/${test_name}-output.yaml"; then
            echo "Found unrendered template variables in ${test_name}-output.yaml"
            cat "test/output/${test_name}-output.yaml"
            exit 1
          fi
          echo "✓ No unrendered templates found in $test_name"
        done

    - name: Validate Kubernetes resources
      run: |
        for test_file in test/test-cases/*.yaml; do
          test_name=$(basename "$test_file" .yaml)
          echo "=== Validating Kubernetes resources for: $test_name ==="
          
          # Check if the test file contains ServiceMonitor resources
          if grep -q "kind: ServiceMonitor" "test/output/${test_name}-output.yaml"; then
            # Check if Prometheus Operator CRDs are installed
            if ! kubectl get crd servicemonitors.monitoring.coreos.com >/dev/null 2>&1; then
              echo "Skipping ServiceMonitor validation as Prometheus Operator CRDs are not installed"
              # Remove ServiceMonitor resources temporarily for validation
              yq eval 'select(.kind != "ServiceMonitor")' "test/output/${test_name}-output.yaml" > "test/output/${test_name}-output-temp.yaml"
              # Validate remaining resources
              if [ -s "test/output/${test_name}-output-temp.yaml" ]; then
                kubectl apply --dry-run=client -f "test/output/${test_name}-output-temp.yaml"
              else
                echo "No resources to validate after removing ServiceMonitor resources"
              fi
              rm "test/output/${test_name}-output-temp.yaml"
            else
              kubectl apply --dry-run=client -f "test/output/${test_name}-output.yaml"
            fi
          else
            kubectl apply --dry-run=client -f "test/output/${test_name}-output.yaml"
          fi
          echo "✓ Kubernetes resources validated successfully for $test_name"
        done

    - name: Check required resources
      run: |
        for test_file in test/test-cases/*.yaml; do
          test_name=$(basename "$test_file" .yaml)
          echo "=== Checking required resources for: $test_name ==="
          if ! grep -q "kind: Deployment\|kind: Service\|kind: ConfigMap\|kind: Secret" "test/output/${test_name}-output.yaml"; then
            echo "Missing required Kubernetes resources in ${test_name}-output.yaml"
            exit 1
          fi
          echo "✓ Required resources found in $test_name"
        done

    - name: Deploy and test resources
      run: |
        for test_file in test/test-cases/*.yaml; do
          test_name=$(basename "$test_file" .yaml)
          namespace="test-${test_name}-$(date +%m%d%H%M)"
          namespace=$(echo "$namespace" | tr '[:upper:]' '[:lower:]' | tr '_' '-' | cut -c 1-63 | sed 's/-$//')
          
          echo "=== Testing $test_name in namespace: $namespace ==="
          kubectl create namespace "$namespace"
          
          # Apply resources and monitor status
          echo "Applying resources..."
          helm template rybbit . -f "$test_file" --namespace "$namespace" | kubectl apply -f - -n "$namespace"
          
          # Immediate check of events and pod status
          echo "=== Initial Status Check ==="
          echo "Deployments:"
          kubectl get deployments -n "$namespace" -o wide
          
          echo -e "\nPods:"
          kubectl get pods -n "$namespace" -o wide
          
          echo -e "\nRecent Events:"
          kubectl get events -n "$namespace" --sort-by='.lastTimestamp' | tail -n 20
          
          # Monitor deployments with continuous updates
          echo -e "\nMonitoring deployments..."
          while true; do
            echo "=== Current Status ==="
            kubectl get deployments,pods -n "$namespace" -o wide
            
            # Check if all deployments are ready
            ready_count=$(kubectl get deployments -n "$namespace" -o jsonpath='{.items[*].status.readyReplicas}' | tr ' ' '\n' | grep -v "^$" | wc -l)
            total_count=$(kubectl get deployments -n "$namespace" -o jsonpath='{.items[*].status.replicas}' | tr ' ' '\n' | grep -v "^$" | wc -l)
            
            if [ "$ready_count" -eq "$total_count" ] && [ "$total_count" -gt 0 ]; then
              echo "All deployments are ready!"
              break
            fi
            
            # Check for any failed pods
            if kubectl get pods -n "$namespace" | grep -q "Error\|CrashLoopBackOff\|ImagePullBackOff\|Terminating"; then
              echo "Found failed or terminating pods. Checking details..."
              kubectl get pods -n "$namespace" | grep -E "Error|CrashLoopBackOff|ImagePullBackOff|Terminating"
              echo -e "\nPod Events:"
              kubectl get events -n "$namespace" --sort-by='.lastTimestamp' | grep -E "Error|Warning|Failed"
              echo -e "\nPod Details:"
              for pod in $(kubectl get pods -n "$namespace" -o jsonpath='{.items[*].metadata.name}'); do
                echo -e "\n=== $pod ==="
                kubectl describe pod -n "$namespace" "$pod" | grep -A 10 "Events:"
              done
              exit 1
            fi
            
            sleep 5
          done
          
          # Cleanup with force delete
          echo "=== Cleaning up ==="
          kubectl delete namespace "$namespace" --force --grace-period=0
          echo "✓ Cleanup completed for $test_name"
        done

  publish:
    needs: test
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: set version
      run: |
        ref=${GITHUB_REF##*/}
        echo "VERSION=${ref#v}" >> $GITHUB_ENV
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.12.3

    - name: Login to OCI Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - name: Print env.VERSION
      run: |
        echo "env.VERSION: ${{ env.VERSION }}"
    - name: Package and Push Helm Chart
      run: |
        echo "=== Updating dependencies ==="
        helm dependency update .
        echo "✓ Dependencies updated successfully"

        echo "=== Packaging chart ==="
        helm package --version ${{ env.VERSION }} .
        echo "✓ Chart packaged successfully"

        echo "=== Pushing to OCI registry ===" 
        helm push rybbit-*.tgz oci://${{ env.REGISTRY }}/library
